CREATE OR REPLACE FUNCTION FC_RETORNA_VLR_GERNEGOCIO
(
    P_NUMCONTRATO IN INT,    
    P_GRUPO IN INT,
    P_CODPROD IN INT
)
/*
AUTOR: Diego Teixeira
DATA: 04/12/2023
OBJETIVO:Retornar o valor de um item da gerencia de negócios da tela de contrato

PARÂMETROS:
    P_NUMCONTRATO: Contrato
    P_GRUPO:    Grupo
    P_CODPROD:  Código do produto
EXEMPLO: SELECT FC_RETORNA_VLR_GERNEGOCIO(18627,2,26435) FROM DUAL;
*/
RETURN FLOAT IS 
    VLRITEM NUMBER := 0; 
BEGIN
    SELECT 
    VALOR INTO VLRITEM
    FROM TCSCPR 
    WHERE NUMCONTRATO = P_NUMCONTRATO 
    AND GRUPO = P_GRUPO AND CODPROD = P_CODPROD;
    
    RETURN VLRITEM;
END;