CREATE OR REPLACE PROCEDURE "STP_INC_TCICTA_PROD" (
       P_CODUSU NUMBER,        -- CÓDIGO DO USUÁRIO LOGADO
       P_IDSESSAO VARCHAR2,    -- IDENTIFICADOR DA EXECUÇÃO. SERVE PARA BUSCAR INFORMAÇÕES DOS PARÂMETROS/CAMPOS DA EXECUÇÃO.
       P_QTDLINHAS NUMBER,     -- INFORMA A QUANTIDADE DE REGISTROS SELECIONADOS NO MOMENTO DA EXECUÇÃO.
       P_MENSAGEM OUT VARCHAR2 -- CASO SEJA PASSADA UMA MENSAGEM AQUI, ELA SERÁ EXIBIDA COMO UMA INFORMAÇÃO AO USUÁRIO.
) AS
       PARAM_CTADEBDEP VARCHAR2(4000);
       PARAM_CODHISDEP_DEB VARCHAR2(4000);
       PARAM_CTACREDCPTDEP VARCHAR2(4000);
       PARAM_CODHISCPTDEP_CRED VARCHAR2(4000);
       PARAM_CTADEBBXDEP VARCHAR2(4000);
       PARAM_CODHISBXDEP_DEB VARCHAR2(4000);
       PARAM_CTACREDBXDEP VARCHAR2(4000);
       PARAM_CODHISBXDEP_CRED VARCHAR2(4000);
       PARAM_CTADEBBXBEM VARCHAR2(4000);
       PARAM_CODHISBXBEM_DEV VARCHAR2(4000);
       PARAM_CTACREDCPTBXBEM VARCHAR2(4000);
       PARAM_CODHISBXBEM_CRED VARCHAR2(4000);
       FIELD_CODPROD NUMBER;
BEGIN

/************************************************************************************************
NOME AUTOR: Diego Teixeira de Almeida
DATA......: 15/06/2023
BANCO DE DADOS: ORACLE
OBJETIVO..: Procedure do botão Cadastrar Contas contábeis da tela de produtos. Esse botão foi criado para poder cadastrar as contas do ativo para que possam depreciar, pois a tela está com um problema onde não está capturando o código do produto quando se tenta vincular as contas do ativo

PARAMETROS DE ENTRADA:
         Contas contábeis e histórico padrão, os mesmos campos contidos na tela Produtos->Bens->Contas do Produto.
EXEMPLO DE USO: SELECT MCTY_RETORNA_MESES_DEPRECIADOS( 21625, 'BRJ844YBMN') FROM DUAL
*************************************************************************************************/
       PARAM_CTADEBDEP := ACT_TXT_PARAM(P_IDSESSAO, 'CTADEBDEP');
       PARAM_CODHISDEP_DEB := ACT_TXT_PARAM(P_IDSESSAO, 'CODHISDEP_DEB');
       PARAM_CTACREDCPTDEP := ACT_TXT_PARAM(P_IDSESSAO, 'CTACREDCPTDEP');
       PARAM_CODHISCPTDEP_CRED := ACT_TXT_PARAM(P_IDSESSAO, 'CODHISCPTDEP_CRED');
       PARAM_CTADEBBXDEP := ACT_TXT_PARAM(P_IDSESSAO, 'CTADEBBXDEP');
       PARAM_CODHISBXDEP_DEB := ACT_TXT_PARAM(P_IDSESSAO, 'CODHISBXDEP_DEB');
       PARAM_CTACREDBXDEP := ACT_TXT_PARAM(P_IDSESSAO, 'CTACREDBXDEP');
       PARAM_CODHISBXDEP_CRED := ACT_TXT_PARAM(P_IDSESSAO, 'CODHISBXDEP_CRED');
       PARAM_CTADEBBXBEM := ACT_TXT_PARAM(P_IDSESSAO, 'CTADEBBXBEM');
       PARAM_CODHISBXBEM_DEV := ACT_TXT_PARAM(P_IDSESSAO, 'CODHISBXBEM_DEV');
       PARAM_CTACREDCPTBXBEM := ACT_TXT_PARAM(P_IDSESSAO, 'CTACREDCPTBXBEM');
       PARAM_CODHISBXBEM_CRED := ACT_TXT_PARAM(P_IDSESSAO, 'CODHISBXBEM_CRED');

       FOR I IN 1..P_QTDLINHAS 
       LOOP                    

            FIELD_CODPROD := ACT_INT_FIELD(P_IDSESSAO, I, 'CODPROD');

            INSERT INTO TCICTA(CODPROD,CODBEM,TIPO,CODCTACTB,CODHISTCTB)
            VALUES            (28264,'<TODOS>',R1.TIPO,R1.CODCTACTB,R1.CODHISTCTB);       



       END LOOP;




-- <ESCREVA SEU CÓDIGO DE FINALIZAÇÃO AQUI> --



END;
