
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SANKHYA"."VW_HOMEOFFICE" ("NUMCONTRATO", "NUNOTADEST", "CODPARC", "NOMEUSU", "ID", "CODPROD", "SEQ", "DHALTER", "ENDERECO", "EMAIL", "STATUS", "NUNICO", "CPF", "QTD") AS 
  SELECT 
 L.NUMCONTRATO
,L.NUNOTADEST 
,L.CODPARC
,P.NOMEPARC AS NOMEUSU
,L.ID
,L.CODPROD 
,L.SEQROLDEST AS SEQ
,L.DHALTER
,D.ENDERECO
,P.EMAIL
,(CASE  WHEN NVL(TO_CHAR(C.AD_DTENTREGUE),'01/01/1900') > '01/01/1900' THEN 'E' ELSE 'EM' END) AS STATUS
,D.NUNICO
,D.CPF
,L.QTD
FROM AD_DISTRIBLOG L
INNER JOIN AD_PLANROL R ON R.NUNOTA = L.NUNOTADEST AND L.SEQROLDEST = R.SEQ
INNER JOIN AD_PLANLSTDISTHO D ON D.NUMCONTRATO = L.NUMCONTRATO AND D.CODLIST = L.CODLIST AND D.CODPARC = L.CODPARC
INNER JOIN TGFPAR P ON P.CODPARC = D.CODPARC
LEFT  JOIN TGFVAR V ON V.NUNOTAORIG = L.NUNOTADEST
INNER JOIN TGFCAB C ON C.NUNOTA = V.NUNOTA
ORDER BY NUMCONTRATO DESC;

