
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SANKHYA"."AD_TGFCSUBMOVR" ("CODBEM", "CODPROD", "CODTIPOPER", "CODUSU", "NUMNOTA", "NUNOTA", "SEQM", "NU", "DTENTSAI", "CODPARC", "NUMCONTRATO"
  ,"CODEMPR","CODEMPNEGOC") AS 
  SELECT
   IBE.CODBEM
  ,IBE.CODPROD
  ,CAB.CODTIPOPER
  ,CAB.CODUSU
  ,CAB.NUMNOTA
  ,B.NUNOTA
  ,ROWNUM AS SEQM
  ,CAB.NUNOTA AS NU
  ,CAB.DTENTSAI
  ,CAB.CODPARC
  ,CAB.NUMCONTRATO
  ,CAB.CODEMP
  ,CAB.CODEMPNEGOC
  FROM TCIIBE IBE
  INNER JOIN AD_TGFISUB B ON B.CODPROD = IBE.CODPROD AND B.CODBEM = IBE.CODBEM
  INNER JOIN TGFCAB CAB ON CAB.NUNOTA = IBE.NUNOTA
  INNER JOIN TGFPRO PRO ON PRO.CODPROD = IBE.CODPROD
  INNER JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
  INNER JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER AND TOP.DHALTER = CAB.DHTIPOPER
  INNER JOIN TSIUSU USU ON CAB.CODUSU = USU.CODUSU
  WHERE B.TIPO = 1
  ORDER BY 1;

