
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SANKHYA"."VW_HOMEOFFICE_PREPARACAO" ("NUNICO", "SEQ", "NUMCONTRATO", "CODPROD", "NUNOTA", "NOME", "EMAIL", "CPF", "ENDERECO", "NUMERO", "COMPL", "BAIRRO", "CEP", "CIDADE", "UF", "HOSTNAME", "LOGINREDE", "RASTREIO", "DTENTREGUE", "STATUS", "CODBEM", "ETIQUETA", "QTD") AS 
  SELECT 
 U.NUNICO
,U.SEQ
,U.NUMCONTRATO
,L.CODPROD
,U.NUNOTA
,U.NOME
,U.EMAIL
,U.CPF
,U.ENDERECO
,U.NUMERO
,U.COMPL
,U.BAIRRO
,U.CEP
,U.CIDADE
,U.UF
,U.HOSTNAME
,U.LOGINREDE
,U.RASTREIO
,U.DTENTREGUE
,(
	CASE WHEN U.STATUS = 'E' THEN 'Entregue'
	WHEN U.STATUS = 'EM' THEN 'Em Trânsito'
	ELSE 'Pendente' END
) AS STATUS
,E.CODBEM
,E.ETIQUETA
,L.QTDNEG AS QTD
FROM  AD_PLANROLUSU U
INNER JOIN AD_PLANROL L ON L.NUNICO = U.NUNICO AND L.NUMCONTRATO = U.NUMCONTRATO AND L.SEQ = U.SEQ
LEFT JOIN AD_TGFIINTE E ON U.NUMCONTRATO = E.NUMCONTRATO AND U.NUNOTA = E.NUNOTA AND L.CODPROD = E.CODPROD AND
L.NUMCONTRATO = E.NUMCONTRATO AND L.NUNOTA = E.NUNOTA AND E.USUARIO = U.NOME
/*
======================================================================
Fim Bloco
======================================================================
*/
UNION
/*
======================================================================
Segundo Bloco
======================================================================
*/
SELECT 
 U.NUNICO
,U.SEQ
,U.NUMCONTRATO
,L.CODPROD
,U.NUNOTADEST AS NUNOTA
,U.NOMEUSU
,U.EMAIL
,U.CPF
,U.ENDERECO
,P.NUMEND
,P.COMPLEMENTO
,BA.NOMEBAI
,P.CEP
,CI.NOMECID
,UF.UF
,'' AS HOSTNAME
,'' AS LOGINREDE
,'' AS RASTREIO
,C.AD_DTENTREGUE
,(
	CASE C.AD_DTENTREGUE WHEN NULL THEN 'PENDENTE'
	ELSE 'ENTREGUE' END
) AS STATUS
,E.CODBEM
,E.ETIQUETA
,U.QTD
FROM  VW_HOMEOFFICE U
INNER JOIN AD_PLANROL L ON L.NUNOTA = U.NUNOTADEST AND L.NUMCONTRATO = U.NUMCONTRATO AND L.SEQ = U.SEQ
INNER JOIN TGFCAB C ON C.NUNOTA = U.NUNOTADEST
INNER JOIN TGFPAR P ON P.CODPARC = U.CODPARC
INNER JOIN TSICID CI ON CI.CODCID = P.CODCID
INNER JOIN TSIUFS UF ON UF.CODUF = CI.UF
INNER JOIN TSIBAI BA ON BA.CODBAI = P.CODBAI
LEFT JOIN AD_TGFIINTE E ON U.NUMCONTRATO = E.NUMCONTRATO AND U.NUNOTADEST = E.NUNOTA AND L.CODPROD = E.CODPROD AND
L.NUMCONTRATO = E.NUMCONTRATO AND L.NUNOTA = E.NUNOTA AND E.USUARIO = U.NOMEUSU;

